### ISSUE TITLE
AutoPlug grabs wrong version of AuctionMaster

### ISSUE THREAD

**Issue by Erisfiregamer1** [Osiris-Team/AutoPlug-Client#168]
**Log**
[Irrelevant in this case, there's no error]
**Expected**
AutoPlug grabs AuctionMaster 4.1 from the new plugin URL.
**Actual**
AutoPlug grabs older version of plugin from previous developer's page (deprecated)
**Steps**
- Install AuctionMaster and AutoPlug
- wait for AutoPlug to grab new plugin release
**Screenshots**
![image](https://user-images.githubusercontent.com/54373833/170893366-605c135b-5cf4-4b64-ab83-d0d15d1b55b4.png)
(Updater grabs plugin from older developer)

**Comment by Osiris-Team** [comment]
You can enter a spigot id to point to the right page (more info in the plugins config).
I can't add exceptions for each plugin.
The way autoplug finds ids is based on the plugin name and author provided in its plugin.yml file.
The new author must also change the name in the plugin.yml file so that autoplug can detect it.
