### ISSUE TITLE
Non-numerical characters are not recorded in plugin versions and availability is wrong

### ISSUE THREAD

**Issue by LordChunk** [Osiris-Team/AutoPlug-Client#24]
When recording versions for plugins AutoPlug seems to remove any non-numerical numbers from the version. 
For example:  dynmap version ``v3.1-beta3a-409`` will be displayed as ``v3.13409`` in the web-interface. 
![image](https://user-images.githubusercontent.com/23651869/92935761-86d33500-f449-11ea-8a64-8d5ab049179b.png)

**Comment by Osiris-Team** [comment]
@LordChunk Yes this feature is intended, because as you can see in your own example there are a lot of different names developers can give their plugin version like "v3.1-beta3a-409". Autoplug removes those characters and only compares the numbers left. This works in 99% of the cases, because beta versions usually have a greater number than stable ones.

**Comment by Osiris-Team** [comment]
@LordChunk In ur example the web-interface says that there are updates available even though the latest version is the same.
I'll take a look on that thx for reporting ;)
