### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ichbestimmtnicht** [Osiris-Team/AutoPlug-Client#31]
As the title says: 

This site can’t be reachedThe web page at https://autoplug.ddns.net/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by Osiris-Team** [comment]
@ichbestimmtnicht Let me quote from my spigot-posts first line: "News: We are updating our website, that's why registration will not work for a while. Sry for the inconvenience!
Get notified when the update is ready: https://discord.gg/GGNmtCC"
https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
