### ISSUE TITLE
Can this be self hosted?

### ISSUE THREAD

**Issue by Magnum97** [Osiris-Team/AutoPlug-Client#40]
First I would like to say this looks amazing. The web interface is so clean and responsive. 
I would however prefer to self host this- is that possible and what steps would I need to take to get this done? I have Minecraft server and webserver hosted on a VPS.

**Comment by Osiris-Team** [comment]
Thanks for the kind words @Magnum97 . It was a lot of work, so I appreciate it.
You can **not** self-host the AutoPlug-Webserver at the moment and I'm not yet sure if you will ever be able to.
Here are some of my reasons why not:
 - AutoPlug-Web uses a lot of resources and optimizing it for self-hosting would mean a lot of work
 - Generally making this available for self-hosting would mean a lot of work
 - Since AutoPlug is one of its kind (and that for a good reason, since nobody wants to go through all that pain of developing it) and we put a lot of effort into developing it, I wouldn't want to share all that precious work for some dude to copy and make it his own
 - You have basically no impact on your Minecraft servers performance when using AutoPlug-Web, since the webserver is hosted by us (compared to other web-panels)
 - You don't need to care about the webservers security and its encryption (SSL)
 - You can access your server from anywhere at any time, without needing to open any extra ports
 - You would have to manually update your web server

Here are some reasons for self-hosting:
 - You wouldn't need to rely on an external service and thus not worry about it being unavailable
 - You wouldn't need to create an account that provides access to your server (not yet, but I'm planning on adding an online console) and thus feel more secure
 - You would have access to the complete code and thus feel more secure
 - I wouldn't have to pay for a webserver every month
 - I wouldn't have to worry about my users' data and its security/protection

I'll leave this issue open for further discussion. Feel free to share your opinion.

**Comment by ahdg6** [comment]
I would like to say this plugin is amazing and thank you for making plugin update autometely possible but if I use this from a country with Internet censorship (like China).
The connection to AutoPlugin-Web would be slow and updater can not work correctly.
As a result,I would prefer to self-hosted this,hope it can come true one day.

**Comment by Osiris-Team** [comment]
@ahdg6 Oh I see. Sry I to hear that :/ I hope the connection is not too slow...
But your point is pretty valid and I'm going to add it to the list.

**Comment by Osiris-Team** [comment]
@ahdg6 Good news for you! I'm planning on making the complete update checking client-side, so that registration and use of AutoPlug-Web will be completely optional!
This should drastically increase the checking time for you. I'll try to make the checking asynchronous, so that all your plugins can be checked at the same time.

**Comment by Osiris-Team** [comment]
@ahdg6 v2.0 now has the search algorithm inside of the client, so your plugin checking speed wont be affected from your internet connection

**Comment by ahdg6** [comment]
> @ahdg6 v2.0 now has the search algorithm inside of the client, so your plugin checking speed wont be affected from your internet connection

wow,that would be awesome,I will try it when I have spare time.
Thank you for your amazing work.

**Comment by Osiris-Team** [comment]
Closing this since it doesn't look like there will be much further discussion.

**Comment by Osiris-Team** [comment]
Self hosted version will be available soon. Im not sure about the price yet but I am thinking of 499€ one time payment with life-time updates. And as alternative monthly payment.
